### ISSUE TITLE
Marker

### ISSUE THREAD

**Issue by leileizhu** [dianwoba/react-native-amap#13]
请问我想在地图上标记多个标记，大约几百个，不知道该怎么实现呢？

**Comment by marshalYuan** [comment]
你好 是目前渲染出几百个marker出现性能问题了 还是什么 能描述清楚点么

**Comment by leileizhu** [comment]
你好。我是想在地图上渲染几百个marker，又不能 
<AMapView initialRegion={{latitude: 31.192199, longitude: 121.503628}} showsUserLocation>
                        <AMapView.Marker/> <AMapView.Marker/><AMapView.Marker/>。。。。。。
                    </AMapView>
这样。在里面加{this.Marker}好像又实现不鸟。所以不知道怎样实现。求大神指教。。。

**Comment by marshalYuan** [comment]
额 这个应该属于jsx的一些常见用法吧
```
{
markers.map(m => <AMapView.Marker ...m />)
}
```
